from selenium import selenium
import unittest, time, re

class populate(unittest.TestCase):
    def setUp(self):
        self.verificationErrors = []
        self.selenium = selenium("localhost", 4444, "*chrome", "http://127.0.0.1:8000/")
        self.selenium.start()
    
    def test_populate(self):
        sel = self.selenium
        sel.open("/login?next=/main_app")
        sel.type("id_username", "usera")
        sel.type("id_location", "boston, ma")
        sel.type("id_terms", "term1, term2")
        sel.type("//form[@id='signup-form']/p[4]/input", "usera@email.com")
        sel.type("id_password1", "password")
        sel.type("id_password2", "password")
        sel.click("//input[@value='Sign Up']")
        sel.wait_for_page_to_load("30000")
        sel.click("link=Add Contact")
        sel.wait_for_page_to_load("30000")
        sel.select("id_salutation", "label=Mr.")
        sel.type("id_first_name", "John")
        sel.type("id_last_name", "Twiddle")
        sel.type("id_job_title", "Ceo")
        sel.type("id_description", "description.")
        sel.type("id_phone", "617-000-0000")
        sel.type("id_email", "john@twiddle.com")
        sel.type("id_street", "123 main street")
        sel.type("id_city", "Boston")
        sel.type("id_state", "MA")
        sel.type("id_country", "USA")
        sel.type("id_im", "johnny147")
        sel.click("//input[@value='submit']")
        sel.click_at("link=Add Contact", "")
        sel.wait_for_page_to_load("30000")
        sel.select("id_salutation", "label=Mrs.")
        sel.type("id_first_name", "Deborah")
        sel.type("id_last_name", "Miller")
        sel.type("id_job_title", "Chief Engineer")
        sel.type("id_description", "description")
        sel.type("id_phone", "617-555-9876")
        sel.type("id_email", "deborah@email.com")
        sel.type("id_street", "12 harpor ave")
        sel.type("id_city", "boston")
        sel.type("id_state", "MA")
        sel.type("id_zip_code", "02143")
        sel.type("id_country", "USA")
        sel.type("id_im", "debby43")
        sel.add_selection("id_introduced_by", "label=John Twiddle")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Contact")
        sel.wait_for_page_to_load("30000")
        sel.select("id_salutation", "label=Dr.")
        sel.type("id_first_name", "Albert")
        sel.type("id_last_name", "Einstein")
        sel.type("id_job_title", "Clerk")
        sel.type("id_description", "description")
        sel.type("id_phone", "617-555-1212")
        sel.type("id_email", "al@mensa.com")
        sel.type("id_street", "12 honey street")
        sel.type("id_city", "New York")
        sel.type("id_state", "NY")
        sel.type("id_zip_code", "01243")
        sel.type("id_country", "USA")
        sel.type("id_im", "al1497")
        sel.add_selection("id_introduced_by", "label=John Twiddle")
        sel.remove_selection("id_introduced_by", "label=John Twiddle")
        sel.add_selection("id_introduced_by", "label=Deborah Miller")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Companies")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "MIcrosoft Inc")
        sel.type("id_street", "44 some street")
        sel.type("id_city", "SomeCity")
        sel.type("id_state", "CA")
        sel.type("id_zip_code", "04499")
        sel.type("id_country", "USA")
        sel.type("id_phone", "210-111-1456")
        sel.type("id_fax", "210-111-0000")
        sel.type("id_description", "microsoft")
        sel.add_selection("id_contacts", "label=Deborah Miller")
        sel.add_selection("id_contacts", "label=John Twiddle")
        sel.remove_selection("id_contacts", "label=Deborah Miller")
        sel.remove_selection("id_contacts", "label=John Twiddle")
        sel.add_selection("id_contacts", "label=Deborah Miller")
        sel.add_selection("id_contacts", "label=John Twiddle")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Companies")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Enterprise Inc")
        sel.type("id_street", "44 Albony Ave")
        sel.type("id_city", "Dorchester")
        sel.type("id_state", "MA")
        sel.type("id_zip_code", "02111")
        sel.type("id_country", "USA")
        sel.type("id_phone", "617-222-9987")
        sel.type("id_fax", "617-000-1102")
        sel.select("id_type", "label=Other")
        sel.type("id_description", "description")
        sel.add_selection("id_contacts", "label=Albert Einstein")
        sel.click("//input[@value='submit']")
        sel.click_at("link=Add Opportunities", "")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Great Job")
        sel.select("id_company_id", "label=MIcrosoft Inc")
        sel.select("id_type", "label=Full time")
        sel.type("id_amount", "$4,000,000")
        sel.select("id_rate", "label=Annual")
        sel.type("id_web", "www.microsoft.com")
        sel.click("id_cover")
        sel.select("id_application", "label=Mail")
        sel.type("id_instruction", "instructions")
        sel.type("id_description", "description")
        sel.select("id_referral", "label=Albert Einstein")
        sel.add_selection("id_contacts", "label=Albert Einstein")
        sel.add_selection("id_contacts", "label=Deborah Miller")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Opportunities")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Another Job")
        sel.select("id_company_id", "label=Enterprise Inc")
        sel.select("id_type", "label=Full time")
        sel.type("id_amount", "6000")
        sel.type("id_web", "enter.com")
        sel.click("id_cover")
        sel.type("id_instruction", "instructions")
        sel.type("id_description", "description")
        sel.select("id_referral", "label=John Twiddle")
        sel.add_selection("id_contacts", "label=John Twiddle")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Task")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "A Thing to Do")
        sel.select("id_contact_id", "label=Deborah Miller")
        sel.select("id_opportunity_id", "label=Great Job")
        sel.select("id_company_id", "label=MIcrosoft Inc")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Task")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Call my mom")
        sel.select("id_contact_id", "label=Deborah Miller")
        sel.select("id_opportunity_id", "label=Great Job")
        sel.select("id_company_id", "label=Enterprise Inc")
        sel.select("id_priority", "label=Lowest")
        sel.select("id_status", "label=Deferred")
        sel.select("id_status", "label=ToDo")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Events")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Carnival of Ages")
        sel.type("id_start", "1/1/2011")
        sel.type("id_end", "1/1/2011")
        sel.type("id_location", "Boston MA")
        sel.select("id_contact_id", "label=Deborah Miller")
        sel.select("id_company_id", "label=MIcrosoft Inc")
        sel.select("id_opportunity_id", "label=Another Job")
        sel.type("id_description", "awesome")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Events")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Event Thingy")
        sel.type("id_start", "9/3/2009")
        sel.type("id_end", "9/3/2010")
        sel.type("id_location", "Boston MA")
        sel.select("id_contact_id", "label=John Twiddle")
        sel.select("id_company_id", "label=Enterprise Inc")
        sel.select("id_opportunity_id", "label=Great Job")
        sel.type("id_description", "thingy")
        sel.click("//input[@value='submit']")
        sel.open("/logout")

        sel.open("/login?next=/main_app")
        sel.type("id_username", "userb")
        sel.type("id_location", "new york, ny")
        sel.type("id_terms", "term a, term b")
        sel.type("//form[@id='signup-form']/p[4]/input", "userb@email.com")
        sel.type("id_password1", "password")
        sel.type("id_password2", "password")
        sel.click("//input[@value='Sign Up']")
        sel.wait_for_page_to_load("30000")
        sel.click("link=Add Contact")
        sel.wait_for_page_to_load("30000")
        sel.select("id_salutation", "label=Mr.")
        sel.type("id_first_name", "Edward")
        sel.type("id_last_name", "Smith")
        sel.type("id_job_title", "Programmer")
        sel.type("id_description", "he programs")
        sel.type("id_phone", "617-000-9494")
        sel.type("id_email", "edsmith@grooveymail.com")
        sel.type("id_street", "23 park street")
        sel.type("id_city", "Dorchester")
        sel.type("id_state", "MA")
        sel.type("id_country", "USA")
        sel.type("id_im", "cuddlemuffins87")
        sel.click("//input[@value='submit']")
        sel.click_at("link=Add Contact", "")
        sel.wait_for_page_to_load("30000")
        sel.select("id_salutation", "label=Mrs.")
        sel.type("id_first_name", "Jeane")
        sel.type("id_last_name", "Arson")
        sel.type("id_job_title", "Chief")
        sel.type("id_description", "She can do it.")
        sel.type("id_phone", "617-555-1901")
        sel.type("id_email", "jars@pinion.com")
        sel.type("id_street", "34 sin sin lane")
        sel.type("id_city", "boston")
        sel.type("id_state", "MA")
        sel.type("id_zip_code", "02111")
        sel.type("id_country", "USA")
        sel.type("id_im", "icandoit99")
        sel.add_selection("id_introduced_by", "label=Edward Smith")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Contact")
        sel.wait_for_page_to_load("30000")
        sel.select("id_salutation", "label=Mr.")
        sel.type("id_first_name", "Luke")
        sel.type("id_last_name", "Pinecone")
        sel.type("id_job_title", "Sandwich Artist")
        sel.type("id_description", "yes")
        sel.type("id_phone", "617-555-0123")
        sel.type("id_email", "luke@pinecone.gov")
        sel.type("id_street", "127 marlboro way")
        sel.type("id_city", "New York")
        sel.type("id_state", "NY")
        sel.type("id_zip_code", "01277")
        sel.type("id_country", "USA")
        sel.type("id_im", "conesforyou42")
        sel.add_selection("id_introduced_by", "label=Jeane Arson")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Companies")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Microsoft Foot Massage")
        sel.type("id_street", "44 elm street")
        sel.type("id_city", "SomeCity")
        sel.type("id_state", "CA")
        sel.type("id_zip_code", "04411")
        sel.type("id_country", "USA")
        sel.type("id_phone", "210-111-1456")
        sel.type("id_fax", "210-111-0000")
        sel.type("id_description", "best foot massage in town")
        sel.add_selection("id_contacts", "label=Jeane Arson")
        sel.add_selection("id_contacts", "label=Edward Smith")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Companies")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Grey Goo Pharmaceuticals")
        sel.type("id_street", "88 Government Plaza")
        sel.type("id_city", "Unknown")
        sel.type("id_state", "DC")
        sel.type("id_zip_code", "00000")
        sel.type("id_country", "USA")
        sel.type("id_phone", "617-123-4567")
        sel.type("id_fax", "617-123-4568")
        sel.select("id_type", "label=Other")
        sel.type("id_description", "Classified")
        sel.add_selection("id_contacts", "label=Edward Smith")
        sel.click("//input[@value='submit']")
        sel.click_at("link=Add Opportunities", "")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Great Job")
        sel.select("id_company_id", "label=Grey Goo Pharmaceuticals")
        sel.select("id_type", "label=Full time")
        sel.type("id_amount", "$4,000,000")
        sel.select("id_rate", "label=Annual")
        sel.type("id_web", "greygoo.com")
        sel.click("id_cover")
        sel.select("id_application", "label=Mail")
        sel.type("id_instruction", "instructions")
        sel.type("id_description", "test subject")
        sel.select("id_referral", "label=Jeane Arson")
        sel.add_selection("id_contacts", "label=Jeane Arson")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Opportunities")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Something to do?")
        sel.select("id_company_id", "label=Microsoft Foot Massage")
        sel.select("id_type", "label=Full time")
        sel.type("id_amount", "6000")
        sel.type("id_web", "enter.com")
        sel.click("id_cover")
        sel.type("id_instruction", "instructions")
        sel.type("id_description", "description")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Task")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Task")
        sel.select("id_contact_id", "label=Jeane Arson")
        sel.select("id_opportunity_id", "label=Great Job")
        sel.select("id_company_id", "label=Microsoft Foot Massage")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Task")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Call his mom")
        sel.select("id_contact_id", "label=Jeane Arson")
        sel.select("id_opportunity_id", "label=Great Job")
        sel.select("id_company_id", "label=Grey Goo Pharmaceuticals")
        sel.select("id_priority", "label=Lowest")
        sel.select("id_status", "label=Deferred")
        sel.select("id_status", "label=ToDo")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Events")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Carnival")
        sel.type("id_start", "1/1/2011")
        sel.type("id_end", "1/1/2011")
        sel.type("id_location", "Boston MA")
        sel.type("id_description", "awesome")
        sel.click("//input[@value='submit']")
        sel.click("link=Add Events")
        sel.wait_for_page_to_load("30000")
        sel.type("id_name", "Event Thingy")
        sel.type("id_start", "9/3/2009")
        sel.type("id_end", "9/3/2010")
        sel.type("id_location", "Boston MA")
        sel.type("id_description", "thingy")
        sel.click("//input[@value='submit']")
        sel.open("/logout")
    
    def tearDown(self):
        self.selenium.stop()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
